### ISSUE TITLE
[BUG] Cannot connect to a postgres database hosted on Amazon AWS on the "Add Data Sources" page. "Test Connection" keeps running for a while but never changes to "Add Data Source".

### ISSUE THREAD

**Issue by prathamSharma25** [chaos-genius/chaos_genius#840]
## Bug
[BUG] Cannot connect to a postgres database hosted on Amazon AWS on the "Add Data Sources" page. "Test Connection" keeps running for a while but never changes to "Add Data Source".
I have tested with a publicly available postgres database, with the details given in the chaos-genius documentation (please refer [this](https://docs.chaosgenius.io/docs/Public_Datasets_Catalog/access_data)). I was able to connect to the public dataset. However, I cannot connect to my own postgres database (hosted on Amazon AWS). I am certain I am entering the correct credentials for the database connection.

## Environment
- **Chaos Genius version**:  0.5.1
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment type**: Deployed locally by cloning the repository and using the `docker-compose up` command

## Current behavior
After deploying chaos-genius locally and starting all services using the `docker-compose up` command, the home page for chaos-genius shows on localhost:8080. On clicking the "Add Data Source" button on the homepage, I am taken to the "Add Data Sources" page. After entering all details correctly for my own postgres database, I click the "Test Connection" button. a "Loading..." message appears. This never changes to "Add Data Source" and just changes back to "Test Connection".

Steps: to reproduce:
1. Clone the repository: `git clone https://github.com/chaos-genius/chaos_genius`
2. Change into the chaos_genius directory: `cd chaos_genius`
3. Start services: `docker-compose up`
4. Navigate to localhost:8080 in browser
5. Click "Add Data Source" button on homepage
6. Fill in all database connection details
7. Click "Test Connection" to test

## Expected behavior
On clicking the "Test Connection" button, it should change to "Add Data Source". Since the credentials are correct, "Test Connection" should be successful and this should happen.

**Comment by suranah** [comment]
Thanks, @prathamSharma25 for raising the issue. We will look into it.

**Comment by rjdp** [comment]
Hey @prathamSharma25 we were able to reproduce same behaviour when we entered wrong port number, which essentially indicates that the datasource was unreachable and we had no way to distinguish whether it was actually unreachable due to wrong connection endpoint or was just taking a lot of time to connect. In either case we must have timeout.

Although the behaviour was same in my case, In your case it might have been a different cause.

Would love to talk about this more on our Community slack channel, you may join [here](https://join.slack.com/t/chaosgenius/shared_invite/zt-140042uac-rrm~xbx9o_aydi6PTmp_Mg)

**Comment by prathamSharma25** [comment]
Hi @rjdp, thank you for your response. I have made sure to enter all database connection details correctly (with correct port number for my DB). I too beleive it is a timeout issue, but I can't know for sure. If it really is a timeout issue, what do you suggest I do to connect to my database? I have joined the Slack channel. Thanks again.

**Comment by rjdp** [comment]
Thanks @prathamSharma25, as the `5432` port of Postgres server was not publicly accessible and you were accessing it using port forwarding via ssh tunnel, and cg backend containers were not able to access ports on localhost outside container we were able to do following to resolve this:  
- Used IP of docker0 bridge in `Host`  field of Add datasource form, can get this IP by running `ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`
- while ssh tunneling bind source port to 0.0.0.0 instead of localhost, by default ssh tunnel will port forward to localhost, cmd to use `ssh -L 0.0.0.0:<host port> ...` , reference for ssh tunnel => `ssh -L [LOCAL_IP:]LOCAL_PORT:DESTINATION:DESTINATION_PORT [USER@]SSH_SERVER`
